name: Node.js Package

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*.*.*-rc*'
      - '*.*.*'

jobs:
  build-alt-win32:
    name: Build alt-node Win32
    runs-on: windows-2019
    needs: [test]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: actions/setup-node@v1
        name: Setup Node.js 14.x
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: cache
        env:
            cache-name: cache-node-modules
        with:
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            path: |
                ~/.npm
                node_modules
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build-alt

      - name: Upload built script
        uses: actions/upload-artifact@v2
        with:
            name: alt-compiled-win32
            path: compiled
            if-no-files-found: error

  build-alt-unix:
    name: Build alt-node Unix
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: actions/setup-node@v1
        name: Setup Node.js 14.x
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: cache
        env:
            cache-name: cache-node-modules
        with:
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            path: |
                ~/.npm
                node_modules
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build-alt

      - name: Upload built script
        uses: actions/upload-artifact@v2
        with:
            name: alt-compiled-unix
            path: compiled
            if-no-files-found: error

  test:
    name: Build & Test (NAPI)
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: actions/setup-node@v1
        name: Setup Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: cache
        env:
            cache-name: cache-node-modules
        with:
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            path: |
                ~/.npm
                node_modules
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      
      - run: npm test
        name: Build & Test

  publish-npm:
    needs: [test, build-alt-win32, build-alt-unix]
    runs-on: windows-2019
    name: Build (NAPI) & Publish (ALL) Node Package Registry
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: actions/setup-node@v2
        name: Setup Node.js 14
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - uses: actions/cache@v2
        id: cache
        env:
            cache-name: cache-node-modules-pnpm
        with:
            key: ${{ runner.os }}-pnpm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            path: |
                ~/.npm
                node_modules
            restore-keys: |
                ${{ runner.os }}-pnpm-${{ env.cache-name }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build
        name: Build

      - name: Download alt-compiled-win32
        uses: actions/download-artifact@v2
        with:
            name: alt-compiled-win32
            path: compiled

      - name: Download alt-compiled-unix
        uses: actions/download-artifact@v2
        with:
            name: alt-compiled-unix
            path: compiled

      - name: Extract version
        id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=TAG::${TAG}

      - name: Bump package.json version
        shell: bash
        run: echo "`jq '.version="${{ steps.version.outputs.TAG }}"' package.json`" > package.json

      - run: npm publish --tag next
        if: contains(steps.version.outputs.TAG, 'rc')
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - run: npm publish
        name: Publish
        if: "!contains(steps.version.outputs.TAG, 'rc')"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    name: Publish Github Package Registry
    needs: test
    runs-on: windows-latest
    if: "!true"
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: actions/setup-node@v2
        name: Setup Node.js 14
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - uses: actions/cache@v2
        id: cache
        env:
            cache-name: cache-node-modules-pgpr
        with:
            key: ${{ runner.os }}-pgpr-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            path: |
                ~/.npm
                node_modules
            restore-keys: |
                ${{ runner.os }}-pgpr-${{ env.cache-name }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build
        name: Build

      - name: Extract version
        id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=TAG::${TAG}

      - name: Bump package.json version
        shell: bash
        run: echo "`jq '.version="${{ steps.version.outputs.TAG }}"' package.json`" > package.json

      - run: npm publish --tag next
        if: contains(steps.version.outputs.TAG, 'rc')
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm publish
        name: Publish
        if: "!contains(steps.version.outputs.TAG, 'rc')"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
